services:
  api:
    container_name: api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
        context: ./Clicker.API/
        dockerfile: Dockerfile
  # client:
  #   container_name: client
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production
  #   build:
  #       context: ./Clicker.Client/
  #       dockerfile: Dockerfile 
  #   depends_on:
  #     - api
  # shell:
  #   container_name: shell
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=production
  #   build:
  #       context: ./Clicker.Shell/
  #       dockerfile: Dockerfile 
  #   depends_on:
  #     - api
  #     - client