param (
    [Parameter(ValueFromPipeline = $true)]$data
)

# inicializace builderu
Initialize-Builder

# generated
Get-GenerateLine $data

$lowerName = [Regex]::Replace($data.Metadata.Name , '\b.', {  $args[0].Value.Tolower() })
$lowerPluralName = [Regex]::Replace($data.Metadata.PluralName , '\b.', {  $args[0].Value.Tolower() })

# hlavicka
Add-Line('<UserControl x:Class="{0}.Views.{2}.{2}ListView_List"' -f $data.Metadata.AppNamespace, $data.Metadata.Modules, $data.Metadata.Name)
Add-Line('                              xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"')
Add-Line('                              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"')
Add-Line('                              xmlns:behaviors="clr-namespace:{0}.Behaviors"'  -f $data.Metadata.AppNamespace, $data.Metadata.Solution)
Add-Line('                              xmlns:apiclient="clr-namespace:{0}.ApiClient.Advanced;assembly={0}.ApiClient.Advanced"' -f $data.Metadata.DataServiceNamespace, $data.Metadata.Solution)
Add-Line('                              xmlns:codelists="clr-namespace:{1}.Codelists;assembly={1}.Codelists"'-f $data.Metadata.AppNamespace, $data.Metadata.Solution)
Add-Line('                              xmlns:common="clr-namespace:{0}.Common;assembly={0}.Common"' -f $data.Metadata.Solution)
Add-Line('                              xmlns:controls="clr-namespace:{0}.Controls"' -f $data.Metadata.AppNamespace, $data.Metadata.Modules, $data.Metadata.Name)
Add-Line('                              xmlns:converters="clr-namespace:{0}.Converters"' -f $data.Metadata.AppNamespace, $data.Metadata.Modules, $data.Metadata.Name)
Add-Line('                              xmlns:d="http://schemas.microsoft.com/expression/blend/2008"')
Add-Line('                              xmlns:dx="http://schemas.devexpress.com/winfx/2008/xaml/core"')
Add-Line('                              xmlns:{3}="clr-namespace:{0}.ViewModels.{2}"' -f $data.Metadata.AppNamespace, $data.Metadata.Modules, $data.Metadata.Name, $lowerName)
Add-Line('                              xmlns:dxlc="http://schemas.devexpress.com/winfx/2008/xaml/layoutcontrol"')
Add-Line('                              xmlns:dxmvvm="http://schemas.devexpress.com/winfx/2008/xaml/mvvm"')
Add-Line('                              xmlns:dxr="http://schemas.devexpress.com/winfx/2008/xaml/ribbon"')
Add-Line('                              xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"')
Add-Line('                              xmlns:views="clr-namespace:{0}.Views"' -f $data.Metadata.AppNamespace, $data.Metadata.Modules, $data.Metadata.Name, $lowerName)
Add-Line('                              xmlns:vm="clr-namespace:{0}.ViewModels.{2}"' -f $data.Metadata.AppNamespace, $data.Metadata.Modules, $data.Metadata.Name, $lowerName)
Add-Line('                              d:DataContext="{{d:DesignInstance Type=vm:{0}ListViewModel}}"' -f $data.Metadata.Name, $data.Metadata.Prefix)
Add-Line('                              d:DesignHeight="400"')
Add-Line('                              d:DesignWidth="{StaticResource {x:Static common:ResourceKeySelector.MinDocumentWidth}}"')
Add-Line('                              mc:Ignorable="d">')

# telo
Add-Line('  <dxmvvm:Interaction.Behaviors>')
Add-Line('    <behaviors:TableViewService TableView="{x:Reference Name=tableView}" />')
Add-Line('  </dxmvvm:Interaction.Behaviors>')
Add-Line('  <dxlc:LayoutGroup>')
Add-Line('    <Grid>')
Add-Line('      <controls:LayoutGridControl x:Name="listGrid"')
Add-Line('                                  ItemsSource="{Binding SourceList}"')
Add-Line('                                  ItemsSourceType="{{x:Type apiclient:{0}ListModel}}"' -f $data.Metadata.Name, $lowerName)
Add-Line('                                  LayoutName="DriverListView_List"')
Add-Line('                                  PermissionId="{{x:Static codelists:PermissionCodelistValues.{0}}}"' -f $data.Metadata.Name, $lowerName)
Add-Line('                                  SelectedItem="{Binding SelectedModel}"')
Add-Line('                                  SelectedItems="{Binding SelectedModels}"')
Add-Line('                                  ViewModelState="{Binding State}">')
Add-Line('        <dxmvvm:Interaction.Behaviors>')
Add-Line('          <dxmvvm:EventToCommand Command="{Binding GridRowDoubleClickAsyncCommand}"')
Add-Line('                                 EventName="MouseDoubleClick"')
Add-Line('                                 PassEventArgsToCommand="True">')
Add-Line('            <dxmvvm:EventToCommand.EventArgsConverter>')
Add-Line('              <converters:IsLeftDoubleClickEventArgsConverter />')
Add-Line('            </dxmvvm:EventToCommand.EventArgsConverter>')
Add-Line('          </dxmvvm:EventToCommand>')
Add-Line('          <dxmvvm:EventToCommand Command="{Binding SelectedModelChangedAsyncCommand}" EventName="SelectedItemChanged" />')
Add-Line('        </dxmvvm:Interaction.Behaviors>')
Add-Line('        <controls:LayoutGridColumn FieldName="Name"')
Add-Line('                                   ReadOnly="True"')
Add-Line('                                   VisibleIndex="0" />')
Add-Line('        <controls:ItaComboBoxGridColumn FieldName="CreatedBy"')
Add-Line('                                        ReadOnly="True"')
Add-Line('                                        VisibleIndex="1" />')
Add-Line('        <controls:ItaDateEditGridColumn FieldName="Created"')
Add-Line('                                        ReadOnly="True"')
Add-Line('                                        VisibleIndex="2" />')
Add-Line('        <controls:ItaComboBoxGridColumn FieldName="ChangedBy"')
Add-Line('                                        ReadOnly="True"')
Add-Line('                                        VisibleIndex="3" />')
Add-Line('        <controls:ItaDateEditGridColumn FieldName="Changed"')
Add-Line('                                        ReadOnly="True"')
Add-Line('                                        VisibleIndex="4" />')
Add-Line('        <controls:LayoutGridColumn FieldName="Deleted"')
Add-Line('                                   ReadOnly="True"')
Add-Line('                                   VisibleIndex="5">')
Add-Line('          <controls:LayoutGridColumn.EditSettings>')
Add-Line('            <controls:ItaCheckEditSettings />')
Add-Line('          </controls:LayoutGridColumn.EditSettings>')
Add-Line('        </controls:LayoutGridColumn>')
Add-Line('        <controls:LayoutGridControl.View>')
Add-Line('          <controls:ItaTableView x:Name="tableView"')
Add-Line('                                 AllowNewRow="False"')
Add-Line('                                 IsDeleteButtonVisible="False"')
Add-Line('                                 Style="{StaticResource {x:Static common:ResourceKeySelector.ListTableViewStyle}}" />')
Add-Line('        </controls:LayoutGridControl.View>')
Add-Line('      </controls:LayoutGridControl>')
Add-Line('      <dx:WaitIndicator Style="{StaticResource {x:Static common:ResourceKeySelector.WaitIndicatorIsSearchingStyle}}" />')
Add-Line('    </Grid>')
Add-Line('  </dxlc:LayoutGroup>')
Add-Line('')

Add-Line('</UserControl>')

# vypisu builder do hostu
Out-Builder
